### ISSUE TITLE
images not uploading

### ISSUE THREAD

**Issue by Luxxy-GF** [PrivateUploader/PrivateUploader#11]
hello i having this issue with the uploading on the image server gallery

![image](https://github.com/PrivateUploader/PrivateUploader/assets/68338577/f4b5512e-ec8e-424b-b103-3a4820213774)

**Comment by Troplo** [comment]
Hi, does this error arise after uploading the file (like when viewing on the Gallery), or during the upload process (doesn't let you upload)?

You could try statically setting the storage path in app/config/tpu.json (absolute path like /home/luxxy/sus2/storage/) and restarting the service, either way I'll have a look a bit later into the issue and push out a fix.

**Comment by Troplo** [comment]
Should be fixed now if you `git pull`, `yarn build` and restart. I was using the wrong variable when referencing the storage location if it was set to the default value causing it to put files in `app/storage`, but when attempting to load the file in the gallery, it would use `storage` instead.
