### ISSUE TITLE
Friends menu when creating group chat/DM shows friends that haven't added you back.

### ISSUE THREAD

**Issue by fzorb** [PrivateUploader/PrivateUploader#19]
So we have this user called Lipi, who is my IRL friend.
![image](https://github.com/PrivateUploader/PrivateUploader/assets/86922118/556d2a09-f22f-449d-b3da-93cb8454cd15)
He has not yet accepted my friend request, but, when I try to start a DM, he shows up, even though he has not accepted my friend request.
![image](https://github.com/PrivateUploader/PrivateUploader/assets/86922118/5a05b789-fca3-45fe-a044-467c8ba326a2)
Then I get this notification.
![image](https://github.com/PrivateUploader/PrivateUploader/assets/86922118/7bad346c-2e87-4e4c-b468-f17e7897becf)

**Comment by Troplo** [comment]
Fixed in api-v4 branch where all new TPU improvements are being made (not yet production ready though)
